@startuml "Диаграмма активности игрового процесса"

|Загадывающий|
start


:Загадывает слово;
|Отгадывающий|
:Называет букву;
|Система|
if (Буква входит в слово?) then(Да)
:Рисует букву над\nместом где она находится\nв слове в полном кол-ве;
else(Нет)
:Рисует очередную часть тела;
end if
if (Нарисовано все тело?) then(Да)
:Завершение игры. Отгадывающий проиграл;
stop
else(Нет)
if (Отгадано все слово?) then(Да)
:Завершение игры. Игроки меняются ролями;
stop
else(Нет)
:Переход в начало процесса;
stop

@enduml